### ISSUE TITLE
請教一下 如果是不同的是顯示屏該如何調整

### ISSUE THREAD

**Issue by HotdogWang** [xangin/eink-weather-board#1]
你好 我是一個 ESPHome 的新手，碰了一陣子的 HA
最近一樣想把時間天氣狀態用電子紙顯示，剛好逛到你的 repo
但是我手賤硬體設備買的跟你的不一樣 QQ，到手後才發現我想的太天真了

不知道是不是調整下面這些參數就有機會可以使用？

```
# Pins for Waveshare ePaper ESP Board
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

# Now render everything on the ePaper screen.
display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 7.50inV2
    update_interval: never
    id: my_display
    rotation: 270°
```

順手附上我購買的顯示屏，希望可以指點迷津🙏
https://www.good-display.cn/product/386.html

---

額外是一個小 issue /font/materialdesigniconswebfont.ttf 沒有 `-` 但是yaml 裡面有
